live:
  password: ${MEALFIT_PASSWORD}
  theme_id: "80304701492" # Copy of Live Theme
  store: mealfit-dev.myshopify.com

development:
  password: ${MEALFIT_PASSWORD}
  theme_id: "80304668724" #2020-01-11 Order Form Validation [MC] Dev
  store: mealfit-dev.myshopify.com
